# Generated by Django 4.0.1 on 2022-01-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project Name', max_length=50)),
                ('creation_time', models.DateTimeField(auto_now=True, help_text='Project Creation Time.')),
            ],
        ),
    ]
