# Generated by Django 4.0.1 on 2022-01-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_time',
            field=models.DateTimeField(help_text='Project completion time', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Project creation time.'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=100)),
                ('description', models.TextField(help_text='Task description')),
                ('time_estimate', models.IntegerField(help_text='Time in hours required to complete the task.')),
                ('completed', models.BooleanField(default=False, help_text='Task completion status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectm.project')),
            ],
        ),
    ]
